name: python37-codeghar
version: 3.7.2
summary: Python 3.7
description: |
  Install Python 3.7 as a snap.

type: app
grade: devel
confinement: strict

apps:
  python37:
    command: bin/python3.7
  pydoc3:
    command: bin/python3.7 -m pydoc
  pip3:
    command: bin/python3.7 -m pip

parts:
  python37:
    plugin: autotools
    source: https://github.com/python/cpython.git
    source-tag: v3.7.2
